version: '3.8'

networks:
  cogniflow_network:
    driver: bridge

services:
  # The Frontend React App
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
      - NO_DATABASE_MODE=true 
    stdin_open: true 
    tty: true
    depends_on:
      - api-gateway
    networks:
      - cogniflow_network  # The API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./services/api-gateway:/usr/src/app
      - /usr/src/app/node_modules    depends_on:
      users-service:
        condition: service_started 
      courses-service:
        condition: service_started
      authentication-service:
        condition: service_started 
      learning-analytics-service:
        condition: service_started
      ai-tutor-service:
        condition: service_started
    environment:
      - NODE_ENV=development
      - NO_DATABASE_MODE=true 
    networks:
      - cogniflow_network
  # Authentication Service (No Database Mode)
  authentication-service:
    build: ./services/authentication
    ports:
      - "8005:8005"
    volumes:
      - ./services/authentication:/code
    environment:
      - PYTHONPATH=/code
      - NO_DATABASE_MODE=true
      - JWT_SECRET_KEY=dev-secret-key-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - BCRYPT_ROUNDS=12
    networks:
      - cogniflow_network

  # Users Microservice (No Database Mode)
  users-service:
    build: ./services/users-service
    volumes:
      - ./services/users-service:/code
    environment:
      - PYTHONPATH=/code
      - NO_DATABASE_MODE=true 
    networks:
      - cogniflow_network

  # Courses Microservice (No Database Mode)
  courses-service:
    build: ./services/courses-service
    volumes:
      - ./services/courses-service:/code
    environment:
      - PYTHONPATH=/code
      - NO_DATABASE_MODE=true 
    networks:
      - cogniflow_network
  # Learning Analytics Microservice (No Database Mode)
  learning-analytics-service:
    build: ./services/learning-analytics
    volumes:
      - ./services/learning-analytics:/code
    environment:
      - PYTHONPATH=/code
      - NO_DATABASE_MODE=true 
    networks:
      - cogniflow_network
  # Notifications Microservice (No Database Mode)
  notifications-service:
    build: ./services/notifications-service
    ports:
      - "8003:8003"
    volumes:
      - ./services/notifications-service:/code
    environment:
      - PYTHONPATH=/code
      - NO_DATABASE_MODE=true
      - EMAIL_ENABLED=false
      - USER_SERVICE_URL=http://users-service:8001
      - COURSES_SERVICE_URL=http://courses-service:8002
      - ANALYTICS_SERVICE_URL=http://learning-analytics-service:8004
    networks:
      - cogniflow_network

  # AI Tutor Service - Conversational AI, spaced repetition, adaptive content
  ai-tutor-service:
    build: ./services/ai-tutor-service
    ports:
      - "8006:8006"
    volumes:
      - ./services/ai-tutor-service:/code
    environment:
      - PYTHONPATH=/code
      - NO_DATABASE_MODE=true
    networks:
      - cogniflow_network
